mysqlafkar:
  image: mysqlafkar
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: afkar
    MYSQL_PASSWORD: root
  ports:
    - "3333:3306"

web:
  image: afkarenspring
  ports:
    - "8080:8080"
  environment:
    SPRING_DATASOURCE_URL: jdbc:mysql://mysqlafkar:3306/afkar
  links:
    - mysqlafkar

frontend:
  image: afkarfrontend
  ports:
    - "3000:3000"
  links:
    - web

